# Site settings
title: "Fauzia & Matthew's Wedding"
email: wedding@mgardner.me
description: "Fauzia & Matthew's Wedding site. Find event info, RSVP, browse a gallery, and access our gift registries."
baseurl: ""
url: "http://wedding.mgardner.me"

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
